### ISSUE TITLE
Build 718e304 fails - map_extractor issue

### ISSUE THREAD

**Issue by drmike** [ProjectSkyfire/SkyFire.548#444]
Greets:

Trying a fresh compile on a Ubuntu 12.04 box. Following the most recent build listed as being successful listed here:

https://travis-ci.org/ProjectSkyfire/SkyFire_5xx/builds/32823632

Getting this:
[ 23%] Building CXX object src/server/worldserver/CMakeFiles/worldPCH.cpp_dephelp.dir/PrecompiledHeaders/worldPCH.cpp.o
Linking CXX shared module libScriptPCH.cpp_dephelp.so
[ 23%] Built target ScriptPCH.cpp_dephelp
[ 23%] Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/dbcfile.cpp.o
[ 23%] Building CXX object src/tools/map_extractor/CMakeFiles/mapextractor.dir/loadlib.cpp.o
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In member function ‘void ChunkedFile::free()’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:82:15: error: ‘chunk’ does not name a type
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:85:5: error: expected ‘;’ before ‘chunks’
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:85:18: error: could not convert ‘((ChunkedFile_)this)->ChunkedFile::chunks.std::multimap<_Key, _Tp, _Compare, _Alloc>::clear with _Key = std::basic_string, _Tp = FileChunk_, _Compare = std::lessstd::basic_string<char >, _Alloc = std::allocator, FileChunk_> >’ from ‘void’ to ‘bool’
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:87:18: error: expected ‘)’ before ‘;’ token
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In function ‘bool IsInterestingChunk(const u_map_fcc&)’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:103:31: error: range-based-for loops are not allowed in C++98 mode
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In member function ‘void ChunkedFile::parseChunks()’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:125:40: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x [enabled by default]
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:125:61: error: no matching function for call to ‘FileChunk::FileChunk()’
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:125:61: note: candidates are:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: FileChunk::FileChunk()
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: candidate expects 0 arguments, 2 provided
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: FileChunk::FileChunk(const FileChunk&)
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: candidate expects 1 argument, 2 provided
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:127:30: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x [enabled by default]
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:127:72: error: deducing from brace-enclosed initializer list requires #include
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:127:72: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x [enabled by default]
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In member function ‘FileChunk_ ChunkedFile::GetChunk(const string&)’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:138:10: error: ‘range’ does not name a type
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:139:23: error: ‘range’ was not declared in this scope
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In destructor ‘FileChunk::~FileChunk()’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:147:15: error: ‘subchunk’ does not name a type
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:150:5: error: expected ‘;’ before ‘subchunks’
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:150:21: error: could not convert ‘((FileChunk_)this)->FileChunk::subchunks.std::multimap<_Key, _Tp, _Compare, _Alloc>::clear with _Key = std::basic_string, _Tp = FileChunk_, _Compare = std::lessstd::basic_string<char >, _Alloc = std::allocator, FileChunk_> >’ from ‘void’ to ‘bool’
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:151:1: error: expected primary-expression before ‘}’ token
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:151:1: error: expected ‘)’ before ‘}’ token
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:151:1: error: expected primary-expression before ‘}’ token
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:151:1: error: expected ‘;’ before ‘}’ token
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In member function ‘void FileChunk::parseSubChunks()’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:168:40: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x [enabled by default]
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:168:64: error: no matching function for call to ‘FileChunk::FileChunk()’
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:168:64: note: candidates are:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: FileChunk::FileChunk()
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: candidate expects 0 arguments, 2 provided
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: FileChunk::FileChunk(const FileChunk&)
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib/loadlib.h:76:7: note: candidate expects 1 argument, 2 provided
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:170:33: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x [enabled by default]
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:170:75: error: deducing from brace-enclosed initializer list requires #include
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:170:75: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x [enabled by default]
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp: In member function ‘FileChunk_ FileChunk::GetSubChunk(const string&)’:
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:181:10: error: ‘range’ does not name a type
/home/drmike/SkyFire_5xx/src/tools/map_extractor/loadlib.cpp:182:23: error: ‘range’ was not declared in this scope
make[2]: **\* [src/tools/map_extractor/CMakeFiles/mapextractor.dir/loadlib.cpp.o] Error 1
make[1]: **\* [src/tools/map_extractor/CMakeFiles/mapextractor.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
Linking CXX shared module libworldPCH.cpp_dephelp.so
[ 23%] Built target worldPCH.cpp_dephelp

What's strange is with the linked to success build, there's no mention of 'mapextractor.dir' in there. I am running the cmake as "cmake -DSCRIPTS=1 .." as per the build.

The 1024 build with master 397823a worked fine. Well at least it compiled.

edit: If this is the wrong place to list this, please kindly direct me to the correct site.  thanks
